### ISSUE TITLE
Module not found: Can't resolve 'fs' When building.

### ISSUE THREAD

**Issue by bhdurak** [techwriterkoduje/next-js-redoc#1]
Greetings, 

I ahve watched your presentation on youtube and I have cloned and tried to run the code. I have installed the dependencies and when I try to run via npm run dev or via npm run build, I get Module not found: Can't resolve 'fs' error. 

It occurs when we try to use <RedocStandalone /> component in client side. But this should be doing a Server Side Generation. What's the solution here?

**Comment by pensjonatus** [comment]
Hi @bhdurak, the problem is with versions of dependencies. The project has open versions in `package.json` so if you do a fresh install, it's free to grab the latest. It also has a `yarn.lock` which specifies which versions worked when I created this POC.

If you run `npm i`, it ignores `yarn.lock` and creates a `package-lock.json`. And as it does the install, it grabs the versions of packages that won't work.

To solve your issue:
1. Delete the `node_modules` folder and the `package-lock.json` file.
2. Run `yarn` to install dependencies.
3. Use yarn commands instead of npm, e.g., `yarn build`.

I updated the README file to not mention `npm`. 

I hope this helps.
